spring:
  threads:
    virtual:
      enabled: false
  application:
    name: concurrency-demo
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      logging:
        slow-indicator-threshold: 1
downstream:
  health:
    url: http://localhost:8087/actuator/health
