spring:
  threads:
    virtual:
      enabled: false
  application:
    name: concurrency-demo
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health

downstream:
  health:
    url: http://localhost:8087/actuator/health
